services:
  app:
    image: ghcr.io/fajlur79/shortlink:latest
    container_name: shortlink_app
    restart: always

    environment:
      - PORT=3000
      - REDIS_URL=${REDIS_URL}
      - BASE_URL=${BASE_URL}

    ports:
      - "3000:3000"

    logging:
      driver: awslogs
      options:
        awslogs-region: ap-south-1
        awslogs-group: /ecs/shortlink
        awslogs-create-group: "true"

  prometheus:
    image: prom/prometheus:latest
    container_name: shortlink_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  nginx:
    image: nginx:alpine
    container_name: shortlink_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
