global:
  scrape_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'shortlink-app'
    static_configs:
      - targets: ['app:3000']

remote_write:
  - url: ${grafana_url}
    basic_auth:
      username: ${grafana_user}
      password: ${grafana_password}